hangman/urls.py
from django.urls import path

from . import views

app_name = "hangman"
urlpatterns = [
    path('', views.play, name='play'),
    path('reset/', views.reset, name='reset'), 
    path('<str:letter>/', views.shot, name='shot'),
]

pygames/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('four_in_a_row/', include('four_in_a_row.urls')),
    path('hangman/', include('hangman.urls')),
    path('slot_machine/', include('slot_machine.urls')),
    path('admin/', admin.site.urls),
]

hangman/models.py
from django.db import models

class Country(models.Model):
    country = models.CharField(max_length=200)
    def __str__(self) :
        return self.country

hangman/views.py
from string import ascii_uppercase as letters
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
import random
import re

from .models import Country

def play(request):
    #if it is new game, than variable chance don't exists yet. 
    if not request.session.get('game'):
        #create variables in session: chance, letters(from A to Z)
        request.session['game'] = 'on'
        request.session['chance'] = 0
        request.session['letters'] = list(letters)
        #get random country from Database
        country = getCountry()
        #mask word
        masked_word = maskWord(request, country)
        #save word and maksed_word in session
        request.session['word'] = country
        request.session['masked_word'] = masked_word
    return render(request, 'hangman/index.html')

def shot(request, letter):
    #fetch chances from session
    chance = request.session['chance']
    #no more chance or word is guessed, then game is over
    if chance == 11 or chance == 12:
        return HttpResponseRedirect(reverse_lazy('hangman:play'))
    else:
        #fetch word and actual letters from session
        letters = request.session['letters']
        word = request.session['word']
        #remove selected letter
        if letter in letters:
            letters.remove(letter)
            #update letters in session
            request.session['letters'] = letters   
            
            #if selected letter isn't in word
            if not re.search(letter, word):
                chance += 1

        #mask left letters
        masked_word = maskWord(request, word)

        #check if word is guessed
        if not re.search('\*', masked_word):
            chance = 12
        
        #update variables is session
        request.session['chance'] = chance
        request.session['masked_word'] = masked_word
        return HttpResponseRedirect(reverse_lazy('hangman:play'))

def reset(request):
    try:
        del request.session['chance']
        del request.session['game']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse_lazy('hangman:play'))

def getCountry():
    countries_quantity = Country.objects.all().count()
    if countries_quantity == 0:
        return "no data"
    country_id = random.randint(1, countries_quantity)
    country = str(Country.objects.get(pk=country_id))
    country = country.upper()
    return country

def maskWord(request, word):
    letters = request.session['letters']
    letters_str = ''
    for letter in letters:
        letters_str += letter
    letters_str = '[' + letters_str + ']'
    word = re.sub(letters_str, '*', word)
    return word

hangman/templates/hangman/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'hangman/style.css' %}" />
  <title>Hangman_countries</title>
</head>

<body>
  <nav id="nav">
    <a id="nav" href="/">PyGames</a id="nav">
  </nav>
  <h1>{{ request.session.masked_word }}</h1>
  {% if request.session.chance == 11 %}
  <h1 style="color: red;">{{ request.session.word }}</h1>
  {% endif %}
  {% for letter in request.session.letters %}
  <a id="btn" href="{% url 'hangman:shot' letter %}">{{ letter }}</a>
  {% endfor %}
  <hr />
  {% with chance=request.session.chance|stringformat:"i" %}
  {% with img='hangman/img/hangman_'|add:chance|add:'.png' %}
  <img src="{% static img %}" alt="" />
  {% endwith %}
  {% endwith %}
  <br>
  <br>
  <a id="btn" style="width: 100%;" href="{% url 'hangman:reset' %}">New Game</a>
</body>

</html>